version: '3'

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: mariadb:10.5.8
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
