
spring:
  application:
    name: "test"
  datasource:
    password: test
    username: root
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true

  jpa:
    properties:
      hibernate:
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQLDialect
      org:
        hibernate:
          stat: DEBUG
    show-sql: true
    open-in-view: false
  threads:
    virtual:
      enabled: true

